name: auto-test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_test:
    name: 'Auto test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: 'Setup: node.js'
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18

      - name: 'Install: node.js'
        working-directory: src
        run: yarn install --frozen-lockfile

      # Ubuntu用Rust環境のセットアップ: https://github.com/tauri-apps/tauri-action
      - name: 'Setup: Rust'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 'Test: backend'
        working-directory: src-tauri
        run: cargo test
